version: "3.7"
services:
  app:
    image: ghcr.io/${{REAL_ACTOR}}/fastapi-for-aws-deploy-test:latest
    container_name: docker-fastapi-deploy-server
    ports:
      - 8000:8000
    networks:
      - app

networks:
  app:
    driver: bridge